### ISSUE TITLE
Installation of ncdfFlow in 2021

### ISSUE THREAD

**Issue by algebio** [RGLab/ncdfFlow#57]
Hello!

I'm trying to install ncdfFlow in a Windows laptop following the steps in readme.md

I tried the first option and I got this:

> library(BiocInstalller)
Error in library(BiocInstalller) : 
  there is no package called ‘BiocInstalller’

I also tried with BiocManager but I couldn't either.

When I tried with the second option I got this message:

install_github("RGLab/ncdfFlow", ref="trunk")
Downloading GitHub repo RGLab/ncdfFlow@trunk
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/RGLab/ncdfFlow/tarball/trunk'

What can I do?

Thank you for your help!

**Comment by SamGG** [comment]
Hi Juan!
Please read the message completely before typing any command. 
I can help you with the first error although I didn't install this package.
Whenever you got an error `there is no package called`, it means the package was not installed correctly.
Here, you should have needed to `install.packages("BiocInstalller")` first.
In general, stop any procedure at the first error.
As stated in the README, it's easier to install a package from BioConductor. This is what you did when you ran this first command. But, the installation procedure of BioConductor packages has changed and the README does not reflect this now. You should execute those lines one by one and stop at the first error in order to solve it.
```
install.packages("BiocManager")
library(BiocManager)
install("ncdfFlow")
library(ncdfFlow)
```
Once done, enjoy ncdfFlow.
Best.

**Comment by algebio** [comment]
Hi SamGG

Thank you for the help and the advice. Much appreciated.

Regards
Juan
